version: '3.8'

services:
  web:
    build: ./app
    volumes:
      - ./app:/app
      - ./flag.txt:/flag.txt
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    networks:
      - ctf-net

networks:
  ctf-net:
